//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagFind.Strings.@default {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TagFind.Strings.default.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddAppBarButton_Label {
            get {
                return ResourceManager.GetString("AddAppBarButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Description.
        /// </summary>
        public static string AddDescriptionTextBlock_Text {
            get {
                return ResourceManager.GetString("AddDescriptionTextBlock.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackButton_Label {
            get {
                return ResourceManager.GetString("BackButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel_String {
            get {
                return ResourceManager.GetString("Cancel.String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also remove sub-items.
        /// </summary>
        public static string ConfirmDeleteDataItemRemoveChildItemsCheckBox_Content {
            get {
                return ResourceManager.GetString("ConfirmDeleteDataItemRemoveChildItemsCheckBox.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this item has sub-items, they would lost attachment in file explorer system. You can attach them later in wild data items manage page later..
        /// </summary>
        public static string ConfirmDeleteDataItemRemoveSubitemsCheckBox_Content {
            get {
                return ResourceManager.GetString("ConfirmDeleteDataItemRemoveSubitemsCheckBox.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no any mechanism like recycle bins, your items would be removed permanently!.
        /// </summary>
        public static string ConfirmDeleteDataItemWarnNoRecycleBinTextBlock_Text {
            get {
                return ResourceManager.GetString("ConfirmDeleteDataItemWarnNoRecycleBinTextBlock.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this/these items?.
        /// </summary>
        public static string ConfirmDeletingDataItemsDialogTitle_String {
            get {
                return ResourceManager.GetString("ConfirmDeletingDataItemsDialogTitle.String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateDatabaseDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("CreateDatabaseDialog.PrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CreateDatabaseDialog_SecondaryButtonText {
            get {
                return ResourceManager.GetString("CreateDatabaseDialog.SecondaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Database Path At....
        /// </summary>
        public static string CreateDatabasePathAtTextBlock_Text {
            get {
                return ResourceManager.GetString("CreateDatabasePathAtTextBlock.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Database.
        /// </summary>
        public static string CreateDatabaseTextBlock_Text {
            get {
                return ResourceManager.GetString("CreateDatabaseTextBlock.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Time.
        /// </summary>
        public static string CreatedTimeTextBlock_Text {
            get {
                return ResourceManager.GetString("CreatedTimeTextBlock.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string DataItemIsEmptyTextBlock_Text {
            get {
                return ResourceManager.GetString("DataItemIsEmptyTextBlock.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore.
        /// </summary>
        public static string DBContentExplorerPageNavigationViewItem_Content {
            get {
                return ResourceManager.GetString("DBContentExplorerPageNavigationViewItem.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string DBTagEditPageNavigationViewItem_Content {
            get {
                return ResourceManager.GetString("DBTagEditPageNavigationViewItem.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete_String {
            get {
                return ResourceManager.GetString("Delete.String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteAppBarButton_Label {
            get {
                return ResourceManager.GetString("DeleteAppBarButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionTextBlock_Text {
            get {
                return ResourceManager.GetString("DescriptionTextBlock.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditAppBarButton_Label {
            get {
                return ResourceManager.GetString("EditAppBarButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logic Chains.
        /// </summary>
        public static string LogicChainsTextBlock_Text {
            get {
                return ResourceManager.GetString("LogicChainsTextBlock.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Time.
        /// </summary>
        public static string ModifiedTimeTextBlock_Text {
            get {
                return ResourceManager.GetString("ModifiedTimeTextBlock.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string MoveAppBarButton_Label {
            get {
                return ResourceManager.GetString("MoveAppBarButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string NewButton_Label {
            get {
                return ResourceManager.GetString("NewButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenButton_Content {
            get {
                return ResourceManager.GetString("OpenButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string PropertiesTextBlock_Text {
            get {
                return ResourceManager.GetString("PropertiesTextBlock.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenced File.
        /// </summary>
        public static string ReferencedFilePathTextBlock_Text {
            get {
                return ResourceManager.GetString("ReferencedFilePathTextBlock.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveAppBarButton_Label {
            get {
                return ResourceManager.GetString("RemoveAppBarButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Reference.
        /// </summary>
        public static string RemoveDatabaseReferenceButton_Label {
            get {
                return ResourceManager.GetString("RemoveDatabaseReferenceButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Reference.
        /// </summary>
        public static string RemoveReferenceAppBarButton_Label {
            get {
                return ResourceManager.GetString("RemoveReferenceAppBarButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Reference.
        /// </summary>
        public static string RemoveReferenceButton_Content {
            get {
                return ResourceManager.GetString("RemoveReferenceButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton_Label {
            get {
                return ResourceManager.GetString("SaveButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchTextBox_PlaceholderText {
            get {
                return ResourceManager.GetString("SearchTextBox.PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string SelectAppBarButton_Label {
            get {
                return ResourceManager.GetString("SelectAppBarButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        public static string SelectFileButton_Content {
            get {
                return ResourceManager.GetString("SelectFileButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        public static string SelectFolderButton_Content {
            get {
                return ResourceManager.GetString("SelectFolderButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Database Name.
        /// </summary>
        public static string SetDatabaseNameTextBlock_Text {
            get {
                return ResourceManager.GetString("SetDatabaseNameTextBlock.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsAppBarButton_Label {
            get {
                return ResourceManager.GetString("SettingsAppBarButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string SortAppBarButton_Label {
            get {
                return ResourceManager.GetString("SortAppBarButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surnames.
        /// </summary>
        public static string SurnamesTextBlock_Text {
            get {
                return ResourceManager.GetString("SurnamesTextBlock.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Name.
        /// </summary>
        public static string TagNameTextBlock_Text {
            get {
                return ResourceManager.GetString("TagNameTextBlock.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third-Party Attribution.
        /// </summary>
        public static string ThirdPartyAttributionButton_Label {
            get {
                return ResourceManager.GetString("ThirdPartyAttributionButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TitleTextBlock_Text {
            get {
                return ResourceManager.GetString("TitleTextBlock.Text", resourceCulture);
            }
        }
    }
}
